FROM node:12.18

USER node
WORKDIR /home/node/

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node . /home/node/app
COPY --chown=node:node ./entrypoint.dev.sh .
RUN chmod +x entrypoint.dev.sh

EXPOSE 3000
ENTRYPOINT ["sh", "/home/node/app/entrypoint.dev.sh"]
